'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {art,wordArt,categories,type Card,type Word,type Work} from '../lib/words';
type AdminWord=Word&{active:number};
const emptyForm={word:'',syllables:'',meaning:'',category:categories[0],work:'',example:'',scene:'',quote:'',note:'',emoji:''};
// Etkinlik görevlisi / öğretmen paneli: kart onayı, kelime listesi (resim yükleme, YZ ile resim üretme, gizleme) ve yeni kelime ekleme.
export default function AdminPanel(){
const router=useRouter();
const [token,setToken]=useState(''),[logged,setLogged]=useState(false),[view,setView]=useState('cards'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
const [pending,setPending]=useState<Card[]>([]),[words,setWords]=useState<AdminWord[]>([]),[works,setWorks]=useState<Work[]>([]),[ill,setIll]=useState<Record<string,number>>({}),[ai,setAi]=useState(false);
const [form,setForm]=useState(emptyForm),[newWork,setNewWork]=useState({title:'',author:'',period:''});
async function api(url:string,init:RequestInit={}){const r=await fetch(url,{...init,headers:{...init.headers,Authorization:`Bearer ${token}`}});const d=r.status===204?{}:await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı.');return d;}
async function run(label:string,job:()=>Promise<void>){setBusy(label);setError('');setNotice('');try{await job();}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy('');}}
async function loadWords(){const d=await api('/api/admin/words');setWords(d.words);setWorks(d.works);setIll(d.illustrated);setAi(d.ai);setForm(f=>f.work?f:{...f,work:d.works[0]?.id??'__new'});}
const login=()=>run('login',async()=>{const d=await api('/api/admin');setPending(d.cards);await loadWords();setLogged(true);});
const moderate=(id:string,action:string)=>run(id,async()=>{await api('/api/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action})});setPending(p=>p.filter(c=>c.id!==id));});
const changed=async(message:string)=>{await loadWords();router.refresh();setNotice(message);};
const toggle=(w:AdminWord)=>run(w.id,async()=>{await api('/api/admin/words',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'toggle',id:w.id,active:!w.active})});await changed(w.active?`“${w.word}” öğrencilerden gizlendi.`:`“${w.word}” yeniden listede.`);});
const generate=(w:AdminWord)=>run(w.id,async()=>{await api('/api/admin/words',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'generate',id:w.id})});await changed(`“${w.word}” için yeni resim üretildi.`);});
const upload=(w:AdminWord,file?:File)=>{if(file)void run(w.id,async()=>{await api(`/api/admin/words?id=${encodeURIComponent(w.id)}`,{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});await changed(`“${w.word}” resmi güncellendi.`);});};
const add=()=>run('add',async()=>{const d=await api('/api/admin/words',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',word:form,newWork:form.work==='__new'?newWork:undefined})});setForm({...emptyForm,work:form.work==='__new'?'':form.work});setNewWork({title:'',author:'',period:''});await changed(`“${d.word.word}” eklendi. Resmini “Kelimeler” sekmesinden yükleyebilir ya da üretebilirsin.`);setView('words');});
const workTitle=(id:string)=>works.find(k=>k.id===id)?.title??'';
const field=(key:keyof typeof emptyForm,label:string,props:{required?:boolean;placeholder?:string;max?:number;area?:boolean}={})=><label>{label}{props.area?<textarea rows={2} maxLength={props.max} required={props.required} placeholder={props.placeholder} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>:<input maxLength={props.max} required={props.required} placeholder={props.placeholder} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>;
return <><div className="eyebrow">ETKİNLİK GÖREVLİSİ · ÖĞRETMEN</div><h2>Görevli paneli</h2>
{!logged?<><p>Kartları onaylamak ve kelime havuzunu yönetmek için görevli anahtarını gir.</p><form onSubmit={e=>{e.preventDefault();void login();}}><label>Görevli anahtarı<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required/></label><button className="primary" disabled={!!busy}>{busy?'Kontrol ediliyor…':'Giriş yap'}</button></form></>:<>
<div className="chips admin-tabs" role="tablist">{[['cards',`Onay bekleyenler (${pending.length})`],['words',`Kelimeler (${words.length})`],['add','+ Kelime ekle']].map(([k,t])=><button key={k} role="tab" aria-selected={view===k} className={view===k?'chosen':''} onClick={()=>{setView(k);setError('');setNotice('');}}>{t}</button>)}</div>
{view==='cards'&&<>{!pending.length&&<p>Onay bekleyen kart yok.</p>}{pending.map(c=><article className="review" key={c.id}><img src={c.image} alt="İncelenecek kart görseli"/><div><b>{words.find(w=>w.id===c.wordId)?.word??c.wordId} · {c.nickname}</b><p>{c.sentence}</p><small>Görsel tarifi: {c.scene}</small><div className="button-row"><button className="secondary" disabled={!!busy} onClick={()=>moderate(c.id,'approve')}>Yayımla</button><button className="text-button" disabled={!!busy} onClick={()=>moderate(c.id,'reject')}>Yayımlama</button></div></div></article>)}</>}
{view==='words'&&<><p>Kelimeye özel resim yoksa ortak bir hazır resim gösterilir. Resimler kare (1:1) olmalı; yönerge için <code>docs/GORSEL-YONERGESI.md</code>.</p>{words.map(w=><article className={`review admin-word${w.active?'':' hidden-word'}`} key={w.id}><img src={ill[w.id]?wordArt(w.id,ill[w.id]):art(w.image)} alt=""/><div><b>{w.word}</b> <small>· {workTitle(w.work)}{ill[w.id]?'':' · ortak resim'}{w.active?'':' · gizli'}</small><p>{w.meaning}</p><div className="button-row admin-actions"><label className="secondary file-button">Resim yükle<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>{upload(w,e.target.files?.[0]);e.target.value='';}}/></label>{ai&&<button className="secondary" disabled={!!busy} onClick={()=>generate(w)}>{busy===w.id?'Üretiliyor…':'✦ YZ ile üret'}</button>}<button className="text-button" disabled={!!busy} onClick={()=>toggle(w)}>{w.active?'Gizle':'Göster'}</button></div></div></article>)}</>}
{view==='add'&&<form className="admin-form" onSubmit={e=>{e.preventDefault();void add();}}>
{field('word','Kelime *',{required:true,max:40,placeholder:'Örn. Gönül'})}{field('meaning','Anlamı *',{required:true,max:300,area:true})}
<div className="form-row"><label>Kategori<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>{field('syllables','Heceleri',{max:60,placeholder:'gö • nül'})}{field('emoji','Simge',{max:4,placeholder:'✦'})}</div>
<label>Eser *<select value={form.work} onChange={e=>setForm({...form,work:e.target.value})}>{works.map(k=><option key={k.id} value={k.id}>{k.title} · {k.author}</option>)}<option value="__new">+ Yeni eser ekle…</option></select></label>
{form.work==='__new'&&<div className="form-row"><label>Eser adı *<input required maxLength={80} value={newWork.title} onChange={e=>setNewWork({...newWork,title:e.target.value})}/></label><label>Yazar *<input required maxLength={80} value={newWork.author} onChange={e=>setNewWork({...newWork,author:e.target.value})}/></label><label>Dönem<input maxLength={40} placeholder="Örn. 16. yüzyıl" value={newWork.period} onChange={e=>setNewWork({...newWork,period:e.target.value})}/></label></div>}
{field('quote','Eserden alıntı (doğrulanmış)',{max:300,area:true})}{field('note','Eser hakkında kısa not',{max:400,area:true})}{field('example','Örnek cümle * (kelimeyi içermeli)',{required:true,max:240,area:true})}{field('scene','Sahne fikri (resim için)',{max:400,area:true})}
<button className="primary wide" disabled={!!busy}>{busy==='add'?'Ekleniyor…':'Kelimeyi ekle'}</button></form>}
</>}
{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}</>;
}
