'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {byMonth,categories,cover,kinds,kindOf,months,ownArt,slug,themes,type Card,type Word,type Work} from '../lib/words';
import {parseCsv,rowsToEntries,toCsv} from '../lib/csv';
import {fold} from '../lib/game';
import {readSession,writeSession} from './dict-ui';
import {WorkOptions} from './suggest-form';
type AdminWord=Word&{active:number;status:string};
type Fields={word:string;work:string;oldMeaning:string;meaning:string;example:string;addedBy:string;category:string;syllables:string;emoji:string;quote:string;note:string;scene:string};
type Filters={q:string;work:string;status:string;image:string;visible:string};
type ImportResult={row:number;ok:boolean;word?:string;error?:string};
const emptyForm:Fields={word:'',work:'',oldMeaning:'',meaning:'',example:'',addedBy:'',category:categories[0],syllables:'',emoji:'',quote:'',note:'',scene:''};
const noFilter:Filters={q:'',work:'',status:'',image:'',visible:''};
const fieldsOf=(w:AdminWord):Fields=>({...emptyForm,...Object.fromEntries(Object.keys(emptyForm).map(k=>[k,String((w as Record<string,unknown>)[k]??'')]))});
const statusName:Record<string,string>={approved:'Onaylı',pending:'Onay bekliyor',rejected:'Reddedildi'};
const tokenKey='kh-gorevli-anahtari';
function download(name:string,data:BlobPart,type='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
// Kelime formu: öneriyi/kelimeyi düzenlerken ve görevli yeni kelime eklerken ortak kullanılır.
function WordForm({initial,works,busy,submit,extra,children}:{initial:Fields;works:Work[];busy:boolean;submit:(f:Fields)=>void;extra?:boolean;children?:React.ReactNode}){
const [f,setF]=useState(initial);const set=(k:keyof Fields)=>(e:{target:{value:string}})=>setF({...f,[k]:e.target.value});const l=kindOf(works.find(k=>k.id===f.work));
return <form className="admin-form" onSubmit={e=>{e.preventDefault();submit(f);}}>
<div className="form-row"><label>{l.word} *<input required maxLength={80} placeholder={l.wordHint} value={f.word} onChange={set('word')}/></label><label>Tema ve eser *<select required value={f.work} onChange={set('work')}><option value="">Eser seçin…</option><WorkOptions works={works}/>{extra&&<option value="__new">+ Yeni eser ekle…</option>}</select></label></div>
<label>{l.old} *<textarea required rows={2} maxLength={300} placeholder={l.oldHint} value={f.oldMeaning} onChange={set('oldMeaning')}/></label>
<label>{l.now} <small>(boşsa bir üstteki alan kullanılır)</small><textarea rows={2} maxLength={300} value={f.meaning} onChange={set('meaning')}/></label>
<label>Örnek cümle * <small>(kelimeyi içermeli)</small><textarea required rows={2} maxLength={240} value={f.example} onChange={set('example')}/></label>
<label>Ekleyen<input maxLength={40} value={f.addedBy} onChange={set('addedBy')}/></label>
<details><summary>Ek alanlar (hatıra kartı için)</summary><div className="form-row"><label>Kategori<select value={f.category} onChange={set('category')}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Heceler<input maxLength={60} placeholder="bi • lig" value={f.syllables} onChange={set('syllables')}/></label><label>Simge<input maxLength={4} placeholder="✦" value={f.emoji} onChange={set('emoji')}/></label></div>
<label>Eserden alıntı (doğrulanmış)<textarea rows={2} maxLength={300} value={f.quote} onChange={set('quote')}/></label><label>Eser hakkında kısa not<textarea rows={2} maxLength={400} value={f.note} onChange={set('note')}/></label><label>Sahne fikri (resim için)<textarea rows={2} maxLength={400} value={f.scene} onChange={set('scene')}/></label></details>
{children}<div className="button-row start"><button className="primary" disabled={busy}>{busy?'Kaydediliyor…':'Kaydet'}</button></div></form>;}
type NewWorkFields={title:string;author:string;period:string;month:string;kind:string};
function NewWork({value,onChange}:{value:NewWorkFields;onChange:(v:NewWorkFields)=>void}){
return <details className="admin-new-work"><summary>Eser listede yoksa: yeni eser bilgileri (eser alanında “+ Yeni eser ekle…” seçin)</summary><div className="form-row"><label>Eser adı<input maxLength={80} value={value.title} onChange={e=>onChange({...value,title:e.target.value})}/></label><label>Yazar<input maxLength={80} value={value.author} onChange={e=>onChange({...value,author:e.target.value})}/></label></div><div className="form-row"><label>Dönem<input maxLength={40} placeholder="Örn. 16. yüzyıl" value={value.period} onChange={e=>onChange({...value,period:e.target.value})}/></label><label>Ay<select value={value.month} onChange={e=>onChange({...value,month:e.target.value})}><option value="">—</option>{months.map(m=><option key={m}>{m}</option>)}</select></label><label>Tür<select value={value.kind} onChange={e=>onChange({...value,kind:e.target.value})}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label></div></details>;}
// Görevli / öğretmen paneli (/admin): özet, öneriler, kelimeler, görseller, eserler, hatıra kartları, Excel/CSV ve yeni kelime.
export default function AdminApp(){
const [token,setToken]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[logged,setLogged]=useState(false),[view,setView]=useState('summary'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState('');
const [pending,setPending]=useState<Card[]>([]),[cardCount,setCardCount]=useState<Record<string,number>>({}),[words,setWords]=useState<AdminWord[]>([]),[works,setWorks]=useState<Work[]>([]),[ill,setIll]=useState<Record<string,number>>({}),[cov,setCov]=useState<Record<string,number>>({}),[ai,setAi]=useState(false);
const [filters,setFilters]=useState<Filters>(noFilter),[selected,setSelected]=useState<Set<string>>(new Set()),[editing,setEditing]=useState(''),[confirm,setConfirm]=useState(''),[allImages,setAllImages]=useState(false);
const [newWork,setNewWork]=useState<NewWorkFields>({title:'',author:'',period:'',month:'',kind:'eser'}),[formKey,setFormKey]=useState(0),[workForm,setWorkForm]=useState<NewWorkFields>({title:'',author:'',period:'',month:'',kind:'eser'});
const [importText,setImportText]=useState(''),[importPending,setImportPending]=useState(false),[results,setResults]=useState<ImportResult[]>([]);
async function api(url:string,init:RequestInit={},t=token){const r=await fetch(url,{...init,headers:{...init.headers,Authorization:`Bearer ${t}`}});const d=r.status===204?{}:await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı.');return d;}
const post=(body:object,url='/api/admin/words')=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function load(t=token){const [c,d]=await Promise.all([api('/api/admin',{},t),api('/api/admin/words',{},t)]);setPending(c.cards);setCardCount(c.counts??{});setWords(d.words);setWorks(d.works);setIll(d.illustrated);setCov(d.covers);setAi(d.ai);}
async function run(label:string,job:()=>Promise<void>){setBusy(label);setError('');setNotice('');try{await job();}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy('');}}
// Oturum yalnızca bu sekmede hatırlanır; sekme kapanınca yeniden giriş istenir.
useEffect(()=>{const t=readSession<string>(tokenKey,'');if(t)Promise.resolve(t).then(load).then(()=>{setToken(t);setLogged(true);}).catch(()=>writeSession(tokenKey,''));},[]);// eslint-disable-line react-hooks/exhaustive-deps
const login=()=>run('login',async()=>{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Giriş yapılamadı.');await load(d.token);writeSession(tokenKey,d.token);setToken(d.token);setPassword('');setLogged(true);});
const logout=()=>{writeSession(tokenKey,'');setToken('');setPassword('');setLogged(false);};
const done=async(message:string)=>{await load();setSelected(new Set());setConfirm('');setNotice(message);};
const go=(v:string,f:Partial<Filters>={})=>{setView(v);setFilters({...noFilter,...f});setSelected(new Set());setEditing('');setConfirm('');setError('');setNotice('');setResults([]);scrollTo({top:0});};
const names=(ids:string[])=>ids.map(id=>words.find(w=>w.id===id)?.word??id).join(', ');
const setStatus=(ids:string[],status:string)=>run('bulk',async()=>{const d=await post({action:'status',ids,status});await done(`${d.changed} kelime → ${statusName[status].toLocaleLowerCase('tr')}.`);});
const toggle=(ids:string[],active:boolean)=>run('bulk',async()=>{await post({action:'toggle',ids,active});await done(active?`${ids.length} kelime yeniden görünür.`:`${ids.length} kelime öğrencilerden gizlendi.`);});
const remove=(ids:string[])=>run('bulk',async()=>{const d=await post({action:'delete',ids});await done(`${d.deleted.length} kelime silindi.`);if(d.kept.length)setError(`Hatıra kartı bağlı olduğu için silinmedi (gizleyebilirsiniz): ${names(d.kept)}`);});
const update=(w:AdminWord,f:Fields)=>run(w.id,async()=>{await post({action:'update',id:w.id,word:f});setEditing('');await done(`“${f.word}” güncellendi.`);});
const generate=(w:AdminWord)=>run(w.id,async()=>{await post({action:'generate',id:w.id});await done(`“${w.word}” için yeni resim üretildi.`);});
const put=(url:string,file:File)=>api(url,{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});
const upload=(w:AdminWord,file?:File)=>{if(file)void run(w.id,async()=>{await put(`/api/admin/words?id=${encodeURIComponent(w.id)}`,file);await done(`“${w.word}” resmi güncellendi.`);});};
// Toplu görsel: dosya adı kelimeyle eşleşir ("kut.png", "yalnuk.jpg", "Körklüg.webp" → körklüg).
const bulkImages=(files:File[])=>run('images',async()=>{const ok:string[]=[],skipped:string[]=[];for(const file of files){const key=slug(file.name.replace(/\.[^.]+$/,''));const w=words.find(w=>w.id===key)??words.find(w=>slug(w.word)===key);if(!w){skipped.push(file.name);continue;}try{await put(`/api/admin/words?id=${encodeURIComponent(w.id)}`,file);ok.push(w.word);}catch(e){skipped.push(`${file.name} (${e instanceof Error?e.message:'hata'})`);}}
await done(`${ok.length} görsel yüklendi${ok.length?`: ${ok.join(', ')}`:''}.`);if(skipped.length)setError(`Eşleşmeyen / yüklenemeyen: ${skipped.join(', ')}`);});
const uploadCover=(k:Work,file?:File)=>{if(file)void run(k.id,async()=>{await put(`/api/admin/works?id=${encodeURIComponent(k.id)}`,file);await done(`“${k.title}” kapağı güncellendi.`);});};
const addWork=()=>run('work',async()=>{await post({action:'create',...workForm},'/api/admin/works');setWorkForm({title:'',author:'',period:'',month:'',kind:'eser'});await done(`“${workForm.title.trim()}” eserlere eklendi. Kapağını aşağıdan yükleyebilirsin.`);});
const setMonth=(k:Work,month:string)=>run(k.id,async()=>{await post({id:k.id,month},'/api/admin/works');await done(`“${k.title}” → ${month||'ay yok'}.`);});
const setKind=(k:Work,kind:string)=>run(k.id,async()=>{await post({id:k.id,kind},'/api/admin/works');await done(`“${k.title}” → ${kinds[kind as keyof typeof kinds].label}.`);});
const moderate=(id:string,action:string)=>run(id,async()=>{await post({id,action},'/api/admin');await done(action==='approve'?'Kart ortak galeride yayımlandı.':'Kart yayımlanmadı.');});
const add=(f:Fields)=>run('add',async()=>{const d=await post({action:'create',word:f,newWork:f.work==='__new'?newWork:undefined});setNewWork({title:'',author:'',period:'',month:'',kind:'eser'});setFormKey(k=>k+1);await done(`“${d.word.word}” sözlüğe eklendi. Görselini “Görseller”den yükleyebilirsin.`);});
const exportCsv=()=>run('export',async()=>{const r=await fetch('/api/admin/export',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw Error('Dışa aktarılamadı.');download(`sozluk-${new Date().toLocaleDateString('sv')}.csv`,await r.blob());setNotice('Kelime listesi indirildi. Excel’de doğrudan açılabilir.');});
const template=()=>download('sozluk-sablon.csv',toCsv([['Kelime','Eser','Eserdeki anlamı','Günümüzdeki anlamı','Örnek cümle','Ekleyen'],['bilig','Kutadgu Bilig','Bilgi, akıl','Bilgi','Her kitap bana yeni bir bilig kazandırıyor.','Elif, 6-B']]));
const entries=useMemo(()=>rowsToEntries(parseCsv(importText)),[importText]);
const importRows=()=>run('import',async()=>{const d=await post({action:'import',rows:entries,pending:importPending});setResults(d.results);const ok=d.results.filter((r:ImportResult)=>r.ok).length;await load();setNotice(`${ok} / ${d.results.length} satır eklendi.`);});
const workTitle=(id:string)=>works.find(k=>k.id===id)?.title??id;
const approved=words.filter(w=>w.status==='approved'),suggestions=words.filter(w=>w.status==='pending'),missing=approved.filter(w=>!ownArt(w,ill));
// Görünüme göre liste: öneriler, görseller (eksik), bütün kelimeler (filtreli).
const shown=useMemo(()=>{const q=fold(filters.q);return words.filter(w=>(view!=='suggest'||w.status==='pending')&&(view!=='images'||(w.status==='approved'&&(allImages||!ownArt(w,ill))))
&&(!q||fold(`${w.word} ${w.oldMeaning??''} ${w.meaning} ${w.example} ${w.addedBy??''}`).includes(q))&&(!filters.work||w.work===filters.work)&&(!filters.status||w.status===filters.status)
&&(!filters.image||(filters.image==='yes')===!!ownArt(w,ill))&&(!filters.visible||(filters.visible==='yes')===!!w.active));},[words,view,filters,allImages,ill]);
const sel=[...selected].filter(id=>shown.some(w=>w.id===id)),allSel=shown.length>0&&sel.length===shown.length;
const pick=(id:string)=>setSelected(s=>{const n=new Set(s);if(n.has(id))n.delete(id);else n.add(id);return n;});
const bulkBar=<div className="bulk-bar" role="toolbar" aria-label="Seçili kelimeler"><label className="check"><input type="checkbox" checked={allSel} onChange={()=>setSelected(allSel?new Set():new Set(shown.map(w=>w.id)))}/> {sel.length?`${sel.length} seçili`:'Tümünü seç'}</label>
{!!sel.length&&(confirm==='bulk'?<><b>{sel.length} kelime kalıcı olarak silinsin mi?</b><button className="primary danger" disabled={!!busy} onClick={()=>remove(sel)}>Evet, sil</button><button className="text-button" onClick={()=>setConfirm('')}>Vazgeç</button></>
:<><button className="secondary" disabled={!!busy} onClick={()=>setStatus(sel,'approved')}>✓ Onayla</button><button className="secondary" disabled={!!busy} onClick={()=>setStatus(sel,'rejected')}>Reddet</button><button className="secondary" disabled={!!busy} onClick={()=>toggle(sel,false)}>Gizle</button><button className="secondary" disabled={!!busy} onClick={()=>toggle(sel,true)}>Göster</button><button className="text-button danger-text" disabled={!!busy} onClick={()=>setConfirm('bulk')}>Sil</button></>)}</div>;
const row=(w:AdminWord)=>{const own=ownArt(w,ill),cards=cardCount[w.id]??0;return <article className={`admin-row${w.active?'':' hidden-word'}${selected.has(w.id)?' selected':''}`} key={w.id}>
<input type="checkbox" aria-label={`${w.word} seç`} checked={selected.has(w.id)} onChange={()=>pick(w.id)}/>{own?<img src={own} alt=""/>:<span className="admin-placeholder">Görsel<br/>bekleniyor</span>}
<div>{editing===w.id?<WordForm initial={fieldsOf(w)} works={works} busy={busy===w.id} submit={f=>update(w,f)}><button type="button" className="text-button" onClick={()=>setEditing('')}>Vazgeç</button></WordForm>:<>
<div className="row-head"><b>{w.word}</b><span className={`badge ${w.status}`}>{statusName[w.status]}</span>{!w.active&&<span className="badge off">Gizli</span>}{cards>0&&<span className="badge">{cards} kart</span>}<small>{workTitle(w.work)}{w.addedBy?` · ekleyen: ${w.addedBy}`:''} · <code>{w.id}</code></small></div>
<p><i>Eserde:</i> {w.oldMeaning||'—'}{w.meaning!==w.oldMeaning&&<><br/><i>Bugün:</i> {w.meaning}</>}</p><p className="admin-example">“{w.example}”</p>
<div className="button-row admin-actions">{w.status!=='approved'&&<button className="primary" disabled={!!busy} onClick={()=>setStatus([w.id],'approved')}>✓ Onayla</button>}{w.status==='pending'&&<button className="secondary" disabled={!!busy} onClick={()=>setStatus([w.id],'rejected')}>Reddet</button>}
<button className="secondary" disabled={!!busy} onClick={()=>{setEditing(w.id);setConfirm('');}}>Düzenle</button><label className="secondary file-button">{busy===w.id?'Yükleniyor…':own?'Resmi değiştir':'Resim yükle'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>{upload(w,e.target.files?.[0]);e.target.value='';}}/></label>
{ai&&w.status==='approved'&&<button className="secondary" disabled={!!busy} onClick={()=>generate(w)}>✦ YZ ile üret</button>}<button className="text-button" disabled={!!busy} onClick={()=>toggle([w.id],!w.active)}>{w.active?'Gizle':'Göster'}</button>
{confirm===w.id?<><b className="danger-text">{cards?'Hatıra kartı bağlı; silinemez, gizleyin.':'Kalıcı olarak silinsin mi?'}</b>{!cards&&<button className="primary danger" disabled={!!busy} onClick={()=>remove([w.id])}>Evet, sil</button>}<button className="text-button" onClick={()=>setConfirm('')}>Vazgeç</button></>:<button className="text-button danger-text" disabled={!!busy} onClick={()=>setConfirm(w.id)}>Sil</button>}</div></>}</div></article>;};
const list=<>{bulkBar}{shown.map(row)}{!shown.length&&<p className="empty-note">Bu görünümde kelime yok.</p>}</>;
const nav:[string,string,number?][]=[['summary','Özet'],['suggest','Öneriler',suggestions.length],['words','Kelimeler',words.length],['images','Görseller',missing.length],['works','Eserler ve kapaklar'],['cards','Hatıra kartları',pending.length],['io','Excel / CSV'],['add','+ Kelime ekle']];
if(!logged)return <main className="admin-login"><Link className="text-button" href="/">← Sözlüğe dön</Link><div className="eyebrow">ETKİNLİK GÖREVLİSİ · ÖĞRETMEN</div><h1>Görevli paneli</h1><p>Öğrenci önerilerini onaylamak, kelimeleri, görselleri ve kapakları yönetmek için kullanıcı adın ve şifrenle giriş yap.</p>
<form onSubmit={e=>{e.preventDefault();void login();}}><label>Kullanıcı adı<input autoComplete="username" autoFocus value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Şifre<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={!!busy}>{busy?'Kontrol ediliyor…':'Giriş yap'}</button></form>{error&&<p className="error" role="alert">{error}</p>}</main>;
// Özet: eser başına sayılar ve en çok katkı verenler.
const perWork=byMonth(works).map(k=>{const ws=words.filter(w=>w.work===k.id),ok=ws.filter(w=>w.status==='approved');return {k,ok:ok.length,pending:ws.filter(w=>w.status==='pending').length,missing:ok.filter(w=>!ownArt(w,ill)).length,hidden:ok.filter(w=>!w.active).length};});
const contributors=Object.entries(words.filter(w=>w.addedBy&&w.status!=='rejected').reduce<Record<string,{all:number;ok:number}>>((m,w)=>{const c=m[w.addedBy!]??={all:0,ok:0};c.all++;if(w.status==='approved')c.ok++;return m;},{})).sort((a,b)=>b[1].all-a[1].all).slice(0,10);
return <div className="admin-app"><aside><Link className="admin-brand" href="/">Kelimeden <b>Hayale</b><small>Görevli paneli</small></Link><nav aria-label="Panel bölümleri">{nav.map(([k,t,n])=><button key={k} className={view===k?'active':''} aria-current={view===k?'page':undefined} onClick={()=>go(k)}>{t}{n!==undefined&&<span className={`count${k==='suggest'&&n?' hot':''}`}>{n}</span>}</button>)}</nav>
<div className="admin-aside-foot"><Link href="/" target="_blank">Sözlüğü aç ↗</Link><button className="text-button" onClick={logout}>Çıkış yap</button></div></aside>
<main className="admin-main">{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
{view==='summary'&&<><h1>Özet</h1><div className="tiles">{([['Onaylı kelime',approved.length,()=>go('words',{status:'approved'})],['Onay bekleyen öneri',suggestions.length,()=>go('suggest')],['Görseli eksik',missing.length,()=>go('images')],['Eser',works.length,()=>go('works')],['Bekleyen hatıra kartı',pending.length,()=>go('cards')]] as const).map(([t,n,f])=><button key={t} className={`tile${t==='Onay bekleyen öneri'&&n?' hot':''}`} onClick={f}><b>{n}</b>{t}</button>)}</div>
<h2>Eserler</h2><div className="table-wrap"><table><thead><tr><th>Eser</th><th>Ay</th><th>Onaylı</th><th>Bekleyen</th><th>Görseli eksik</th><th>Gizli</th><th>Kapak</th></tr></thead><tbody>{perWork.map(({k,ok,pending:p,missing:m,hidden})=><tr key={k.id}><td><button className="link" onClick={()=>go('words',{work:k.id})}>{k.title}</button></td><td>{k.month||'—'}</td><td>{ok}</td><td>{p?<button className="link hot" onClick={()=>go('suggest',{work:k.id})}>{p}</button>:0}</td><td>{m?<button className="link" onClick={()=>go('images',{work:k.id})}>{m}</button>:'✓'}</td><td>{hidden||''}</td><td>{cov[k.id]?'✓':<button className="link" onClick={()=>go('works')}>yok</button>}</td></tr>)}</tbody></table></div>
<h2>En çok katkı verenler</h2>{contributors.length?<ol className="contributors">{contributors.map(([name,c])=><li key={name}><button className="link" onClick={()=>go('words',{q:name})}>{name}</button><span>{c.all} öneri · {c.ok} onaylı</span></li>)}</ol>:<p className="empty-note">Henüz “ekleyen” bilgisiyle gelen öneri yok.</p>}</>}
{view==='suggest'&&<><h1>Kelime önerileri</h1><p>Öğrencilerin “Kelime ekle” formundan gönderdiği kelimeler. Onaylananlar sözlük kitabına, eser kartlarına ve tahmin oyununa girer; reddedilenler silinmez, “Kelimeler” bölümünden geri alınabilir.</p><div className="filter-bar"><input type="search" placeholder="Ara: kelime, anlam, ekleyen…" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><select aria-label="Eser" value={filters.work} onChange={e=>setFilters({...filters,work:e.target.value})}><option value="">Bütün eserler</option>{works.map(k=><option key={k.id} value={k.id}>{k.title}</option>)}</select></div>{list}</>}
{view==='words'&&<><h1>Kelimeler</h1><div className="filter-bar"><input type="search" placeholder="Ara: kelime, anlam, cümle, ekleyen…" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/>
<select aria-label="Eser" value={filters.work} onChange={e=>setFilters({...filters,work:e.target.value})}><option value="">Bütün eserler</option>{works.map(k=><option key={k.id} value={k.id}>{k.title}</option>)}</select>
<select aria-label="Durum" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Bütün durumlar</option>{Object.entries(statusName).map(([k,t])=><option key={k} value={k}>{t}</option>)}</select>
<select aria-label="Görsel" value={filters.image} onChange={e=>setFilters({...filters,image:e.target.value})}><option value="">Görsel: hepsi</option><option value="yes">Görseli var</option><option value="no">Görseli yok</option></select>
<select aria-label="Görünürlük" value={filters.visible} onChange={e=>setFilters({...filters,visible:e.target.value})}><option value="">Görünürlük: hepsi</option><option value="yes">Görünür</option><option value="no">Gizli</option></select>
{JSON.stringify(filters)!==JSON.stringify(noFilter)&&<button className="text-button" onClick={()=>setFilters(noFilter)}>Filtreleri temizle</button>}</div><p className="result-count">{shown.length} kelime</p>{list}</>}
{view==='images'&&<><h1>Görseller</h1><p>Görseli olmayan kelimeler sözlükte “Görsel bekleniyor” olarak görünür. Dosyaları toplu seçebilirsin; dosya adı kelimeyle eşleşir (<code>kut.png</code>, <code>yalnuk.jpg</code>). Kare (1:1) PNG, JPG veya WEBP, en fazla 8 MB.</p>
<div className="button-row start"><label className="primary file-button">{busy==='images'?'Yükleniyor…':'⇪ Toplu görsel yükle'}<input type="file" multiple accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>{const files=[...e.target.files??[]];e.target.value='';if(files.length)bulkImages(files);}}/></label><label className="check"><input type="checkbox" checked={allImages} onChange={e=>setAllImages(e.target.checked)}/> Görseli olanları da göster</label></div>{!shown.length&&!allImages?<p className="empty-note">Bütün onaylı kelimelerin görseli var. 🎉</p>:list}</>}
{view==='works'&&<><h1>Eserler ve kapaklar</h1><p>Kapaklar “Eserler” bölümündeki kartlarda görünür. Ay, eylem planındaki etkinlik ayıdır; Sözlük Kitabı’nın sırasını ve oyun filtrelerini belirler. Tür, formdaki alan adlarını değiştirir (eser sözlüğü: eserdeki / günümüzdeki anlam · atasözü ve deyim: anlamı / açıklama · yabancı sözcük: Türkçe karşılığı / kökeni).</p><form className="admin-form" onSubmit={e=>{e.preventDefault();void addWork();}}><h2>Yeni eser ekle</h2><div className="form-row"><label>Eser adı<input required minLength={2} maxLength={80} value={workForm.title} onChange={e=>setWorkForm({...workForm,title:e.target.value})}/></label><label>Yazar<input required minLength={2} maxLength={80} value={workForm.author} onChange={e=>setWorkForm({...workForm,author:e.target.value})}/></label></div><div className="form-row"><label>Dönem<input maxLength={40} placeholder="Örn. 16. yüzyıl" value={workForm.period} onChange={e=>setWorkForm({...workForm,period:e.target.value})}/></label><label>Ay<select value={workForm.month} onChange={e=>setWorkForm({...workForm,month:e.target.value})}><option value="">—</option>{months.map(m=><option key={m}>{m}</option>)}</select></label><label>Tür<select value={workForm.kind} onChange={e=>setWorkForm({...workForm,kind:e.target.value})}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label></div><button className="primary" disabled={!!busy}>{busy==='work'?'Ekleniyor…':'Eseri ekle'}</button></form><h2>Kayıtlı eserler</h2>{byMonth(works).map(k=><article className="admin-row" key={k.id}>{cov[k.id]?<img src={cover(k.id,cov[k.id])} alt=""/>:<span className="admin-placeholder">Kapak<br/>bekleniyor</span>}<div><div className="row-head"><b>{k.title}</b><small>{k.author}{k.period?` · ${k.period}`:''} · {approved.filter(w=>w.work===k.id).length} kelime</small></div><div className="button-row admin-actions"><label className="secondary file-button">{cov[k.id]?'Kapağı değiştir':'Kapak yükle'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>{uploadCover(k,e.target.files?.[0]);e.target.value='';}}/></label><select aria-label={`${k.title} ayı`} value={k.month} disabled={!!busy} onChange={e=>setMonth(k,e.target.value)}><option value="">Ay seçilmedi</option>{months.map(m=><option key={m} value={m}>{m} · {themes[m]}</option>)}</select><select aria-label={`${k.title} türü`} value={k.kind??'eser'} disabled={!!busy} onChange={e=>setKind(k,e.target.value)}>{Object.entries(kinds).map(([id,v])=><option key={id} value={id}>{v.label}</option>)}</select><button className="text-button" onClick={()=>go('words',{work:k.id})}>Kelimelerini gör →</button></div></div></article>)}</>}
{view==='cards'&&<><h1>Hatıra kartları</h1><p>Öğrencilerin “Hatıra Kartı” bölümünde oluşturduğu kartlar. Yayımlananlar ortak galeride görünür.</p>{!pending.length&&<p className="empty-note">Onay bekleyen hatıra kartı yok.</p>}{pending.map(c=><article className="admin-row" key={c.id}><img src={c.image} alt="İncelenecek kart görseli"/><div><div className="row-head"><b>{words.find(w=>w.id===c.wordId)?.word??c.wordId}</b><small>{c.nickname} · {new Date(c.createdAt).toLocaleString('tr-TR')}</small></div><p>{c.sentence}</p><small>Görsel tarifi: {c.scene}</small><div className="button-row admin-actions"><button className="primary" disabled={!!busy} onClick={()=>moderate(c.id,'approve')}>Yayımla</button><button className="text-button" disabled={!!busy} onClick={()=>moderate(c.id,'reject')}>Yayımlama</button></div></div></article>)}</>}
{view==='io'&&<><h1>Excel / CSV</h1><section className="io-box"><h2>Dışa aktar</h2><p>Bütün kelimeler (öneriler ve gizliler dahil) Excel’de açılabilen bir dosya olarak iner: kelime, eser, ay, anlamlar, örnek cümle, ekleyen, durum, görsel.</p><button className="primary" disabled={!!busy} onClick={exportCsv}>{busy==='export'?'Hazırlanıyor…':'↓ Kelime listesini indir (.csv)'}</button></section>
<section className="io-box"><h2>İçe aktar</h2><p>Excel’de şu sütunlarla bir tablo hazırla: <b>Kelime · Eser · Eserdeki anlamı · Günümüzdeki anlamı · Örnek cümle · Ekleyen</b>. Tabloyu seçip kopyala ve aşağıya yapıştır ya da “CSV UTF-8” olarak kaydedip dosyayı seç. Eser adı listedeki eserlerden biri olmalı. <button className="text-button" onClick={template}>Örnek şablonu indir</button></p>
<div className="button-row start"><label className="secondary file-button">Dosya seç (.csv)<input type="file" accept=".csv,.tsv,.txt,text/csv,text/plain" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(f){setImportText(await f.text());setResults([]);}}}/></label>{importText&&<button className="text-button" onClick={()=>{setImportText('');setResults([]);}}>Temizle</button>}</div>
<label className="sr-only" htmlFor="import-text">Yapıştırılan tablo</label><textarea id="import-text" rows={6} placeholder="Excel’den kopyaladığın satırları buraya yapıştır…" value={importText} onChange={e=>{setImportText(e.target.value);setResults([]);}}/>
{!!entries.length&&<><p className="result-count">{entries.length} satır okundu{entries.length>500?' — tek seferde en fazla 500 satır aktarılabilir':''}.</p><div className="table-wrap"><table><thead><tr><th>#</th><th>Kelime</th><th>Eser</th><th>Eserdeki anlamı</th><th>Günümüzdeki anlamı</th><th>Örnek cümle</th><th>Ekleyen</th>{!!results.length&&<th>Sonuç</th>}</tr></thead><tbody>{entries.slice(0,500).map((r,i)=>{const res=results.find(x=>x.row===i+1);return <tr key={i} className={res?res.ok?'ok':'bad':''}><td>{i+1}</td><td><b>{r.word}</b></td><td>{r.work}</td><td>{r.oldMeaning}</td><td>{r.meaning}</td><td>{r.example}</td><td>{r.addedBy}</td>{!!results.length&&<td>{res?res.ok?'✓ eklendi':res.error:''}</td>}</tr>;})}</tbody></table></div>
<div className="button-row start"><label className="check"><input type="checkbox" checked={importPending} onChange={e=>setImportPending(e.target.checked)}/> Onay bekleyen öneri olarak ekle</label><button className="primary" disabled={!!busy||entries.length>500||!!results.length} onClick={importRows}>{busy==='import'?'Aktarılıyor…':`${entries.length} satırı içe aktar`}</button></div></>}</section></>}
{view==='add'&&<><h1>Kelime ekle</h1><p>Görevlinin eklediği kelime doğrudan sözlüğe girer. Çok sayıda kelime için “Excel / CSV” bölümünü kullan.</p><WordForm key={formKey} initial={{...emptyForm,work:works[0]?.id??''}} works={works} busy={busy==='add'} submit={add} extra><NewWork value={newWork} onChange={setNewWork}/></WordForm></>}
</main></div>;}
