'use client';
import {useEffect,useRef,useState} from 'react';
import {words,art,type Word,type Card} from '../lib/words';
import QRCode from 'qrcode';

const categories=['Tümü','Hayal','Doğa','Duygu','Sanat','Keşif'];
const styles=['Suluboya','Çizgi roman','Gelecek dünyası'];
export default function Studio(){
const [tab,setTab]=useState('explore'),[category,setCategory]=useState('Tümü'),[query,setQuery]=useState('');
const [selected,setSelected]=useState<Word|null>(null),[step,setStep]=useState(1),[guess,setGuess]=useState(''),[revealed,setRevealed]=useState(false);
const [sentence,setSentence]=useState(''),[scene,setScene]=useState(''),[nickname,setNickname]=useState(''),[style,setStyle]=useState(styles[0]);
const [ai,setAi]=useState(false),[mode,setMode]=useState('demo'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
const [card,setCard]=useState<Card|null>(null),[gallery,setGallery]=useState<Card[]>([]),[loading,setLoading]=useState(false);
const [admin,setAdmin]=useState(false),[token,setToken]=useState(''),[pending,setPending]=useState<Card[]>([]),[logged,setLogged]=useState(false);
const [qr,setQr]=useState('');
useEffect(()=>{let active=true;setQr('');if(card)QRCode.toDataURL(`${location.origin}/?kart=${card.id}`,{width:180,margin:2,color:{dark:'#243130',light:'#ffffff'}}).then(url=>{if(active)setQr(url);}).catch(()=>{});return()=>{active=false;};},[card]);
const dialog=useRef<HTMLDialogElement>(null),focusReturn=useRef<HTMLElement|null>(null);
useEffect(()=>{fetch('/api/config').then(r=>r.json()).then(d=>{setAi(d.ai);setMode(d.ai?'ai':'demo');}).catch(()=>{});const id=new URLSearchParams(location.search).get('kart');if(id){fetch(`/api/cards?id=${encodeURIComponent(id)}`).then(async r=>{const d=await r.json();if(!r.ok)throw Error('Bu kart bulunamadı.');return d;}).then(d=>{setCard(d.card);setSelected(words.find(w=>w.id===d.card.wordId)||null);setStep(4);}).catch(e=>setError(e.message));}},[]);
useEffect(()=>{if(selected||admin){focusReturn.current=document.activeElement as HTMLElement;dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();focusReturn.current?.focus();}},[selected,admin]);
async function loadGallery(){setLoading(true);setError('');try{const r=await fetch('/api/cards');const d=await r.json();if(!r.ok)throw Error(d.error);setGallery(d.cards);}catch(e){setError(e instanceof Error?e.message:'Sözlük yüklenemedi.');}finally{setLoading(false);}}
function changeTab(next:string){setTab(next);setError('');if(next==='gallery')void loadGallery();}
function choose(word:Word){setSelected(word);setStep(1);setGuess('');setRevealed(false);setSentence('');setScene('');setNickname('');setStyle(styles[0]);setCard(null);setError('');setNotice('');}
function close(){if(busy)return;setSelected(null);setAdmin(false);setToken('');setPending([]);setLogged(false);setError('');setNotice('');if(location.search.includes('kart='))history.replaceState(null,'',location.pathname);}
function goCreate(){document.getElementById('words')?.scrollIntoView({behavior:'smooth'});document.getElementById('search')?.focus({preventScroll:true});}
async function create(){if(!selected||busy)return;setBusy(true);setError('');try{const r=await fetch('/api/cards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wordId:selected.id,sentence,scene,nickname,style,mode})});const d=await r.json();if(!r.ok)throw Error(d.error);setCard(d.card);setStep(4);}catch(e){setError(e instanceof Error?e.message:'Kart oluşturulamadı.');}finally{setBusy(false);}}
async function copy(){if(!card)return;try{await navigator.clipboard.writeText(`${location.origin}/?kart=${card.id}`);setNotice('Kartının bağlantısı kopyalandı.');}catch{setNotice(`Kart bağlantın: ${location.origin}/?kart=${card.id}`);}}
async function download(){if(!card||!selected)return;setError('');try{const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=1700;const c=canvas.getContext('2d')!;c.fillStyle='#faf6ee';c.fillRect(0,0,1000,1700);const img=new Image();img.src=card.image;await img.decode();const scale=Math.max(880/img.width,600/img.height);c.save();c.beginPath();c.rect(60,140,880,600);c.clip();c.drawImage(img,60+(880-img.width*scale)/2,140+(600-img.height*scale)/2,img.width*scale,img.height*scale);c.restore();c.fillStyle='#de593a';c.font='bold 25px Arial';c.fillText('KELİMEDEN HAYALE  /  TEKNOFEST HATIRASI',60,85);c.fillStyle='#202a30';c.font='bold 78px Georgia';c.fillText(selected.word,60,845);function wrap(text:string,y:number,size:number,font='Arial'){c.font=`${size}px ${font}`;let line='';for(const word of text.split(' ')){const next=line+word+' ';if(c.measureText(next).width>870){c.fillText(line,60,y);line=word+' ';y+=size*1.45;}else line=next;}c.fillText(line,60,y);return y+size*1.45;}let y=wrap(selected.meaning,910,28);y=wrap('“'+card.sentence+'”',y+40,34,'Georgia');c.font='24px Arial';c.fillText(card.nickname,60,Math.max(1460,y+25));c.fillStyle='#6d7374';c.font='20px Arial';c.fillText(new Date(card.createdAt).toLocaleDateString('tr-TR')+'  ·  '+(card.mode==='ai'?'Yapay zekâ görseli':'Hazır görselle oluşturuldu'),60,1530);c.fillText('Örnek kelime havuzu · '+card.id.slice(0,8).toUpperCase(),60,1600);if(qr){const q=new Image();q.src=qr;await q.decode();c.drawImage(q,760,1435,180,180);}const url=canvas.toDataURL('image/png');const a=document.createElement('a');a.download=`teknofest-${selected.id}-${card.id.slice(0,8)}.png`;a.href=url;a.click();setNotice('Hatıra kartın indirildi.');}catch{setError('Görsel indirilemedi. Yazdır seçeneğini kullanabilirsin.');}}
async function loadAdmin(){setError('');setLoading(true);try{const r=await fetch('/api/admin',{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw Error(d.error);setPending(d.cards);setLogged(true);}catch(e){setError(e instanceof Error?e.message:'Panel açılamadı.');}finally{setLoading(false);}}
async function moderate(id:string,action:string){setBusy(true);setError('');try{const r=await fetch('/api/admin',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({id,action})});if(!r.ok)throw Error('İşlem kaydedilemedi.');setPending(p=>p.filter(c=>c.id!==id));}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy(false);}}
const filtered=words.filter(w=>(category==='Tümü'||w.category===category)&&`${w.word} ${w.meaning}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));
const sentenceValid=!!selected&&sentence.trim().length>=10&&sentence.toLocaleLowerCase('tr').includes(selected.word.toLocaleLowerCase('tr'));
return <>
<header className="header"><a className="brand" href="/" aria-label="Kelimeden Hayale ana sayfa"><span className="brand-icon">k<span>h</span><i>✦</i></span><span>Kelimeden<br/><b>Hayale</b></span></a><nav aria-label="Ana menü"><button className={tab==='explore'?'active':''} onClick={()=>changeTab('explore')}>Kelime atölyesi</button><button className={tab==='gallery'?'active':''} onClick={()=>changeTab('gallery')}>Ortak sözlüğümüz <span className="nav-dot"/></button><button className={tab==='about'?'active':''} onClick={()=>changeTab('about')}>Nasıl çalışır?</button></nav><span className="festival">TEKNOFEST <small>KEŞFET. HAYAL ET. ÜRET.</small></span></header>
<main>
{tab==='explore'&&<>
<section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="live-dot"/> KELİMELERİN DÜNYASINA BİR YOLCULUK</div><h1>Bir kelime.<br/>Binbir <em>hayal.</em><span className="spark">✳</span></h1><p>Geçmişin kelimeleri, senin hayal gücün.<br/>Bir kelime keşfet, ona kendi dünyandan bak.<br/>Sana özel bir TEKNOFEST hatırası oluştur.</p><div className="hero-actions"><button className="primary" onClick={goCreate}>Kelimemi keşfet <span>↗</span></button><button className="text-button" onClick={()=>choose(words[Math.floor(Math.random()*words.length)])}>✧ Bana bir kelime seç</button></div><div className="hero-foot"><span>◷ 3–5 dakikalık bir keşif</span><span>✦ Hayal gücün yeterli</span></div></div><div className="hero-art" aria-label="Örnek tahayyül sözlük kartı"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="floating-label">Hayalin, bir hatıraya dönüşsün.</span><div className="paper-behind"/><article className="hero-card"><div className="card-art"><img src="/art/clouds.png" alt="Bulutların üzerinde uzanan düşsel bir gökyüzü"/><span className="art-label">BİR KELİME, BENİM DÜNYAM</span><span className="art-sun">✷</span></div><div className="hero-card-body"><div className="word-line"><h2>Tahayyül</h2><span>isim</span></div><p>Bir şeyi zihinde canlandırma,<br/>hayal etme.</p><blockquote>“Bulutların ötesinde yeni bir<br/>dünya tahayyül ediyorum.”</blockquote><div className="sample-foot"><span>✦ Bir kelime kâşifi</span><span>ÖRNEK KART</span></div></div></article><span className="sticker">Bu hayalde<br/><b>sen varsın!</b><span>↗</span></span><span className="floating-star">✧</span></div></section>
<section className="journey-strip" aria-label="Üç adımda sözlük kartı"><div><span className="step-icon lilac">01</span><p><b>Bir kelime keşfet</b><small>Anlamına yeni bir kapı aç.</small></p></div><span className="strip-arrow">⤳</span><div><span className="step-icon peach">02</span><p><b>Hayalini anlat</b><small>Kendi cümlenle ona hayat ver.</small></p></div><span className="strip-arrow">⤳</span><div><span className="step-icon sage">03</span><p><b>Hatıranı yanında götür</b><small>Görselli sözlük kartın senin olsun.</small></p></div></section>
<section id="words" className="words-section"><div className="section-heading"><div><div className="eyebrow">HER KELİME YENİ BİR BAŞLANGIÇ</div><h2>Bugün hangi kelime <em>senin?</em></h2><p>Seni meraklandıran bir kelimeyi seç. Gerisini hayal gücüne bırak.</p></div><span className="count">{words.length} kelime · Sonsuz hayal</span></div><div className="filters"><div className="chips" aria-label="Kelime kategorileri">{categories.map(c=><button key={c} className={category===c?'chosen':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><label className="search"><span>⌕</span><input id="search" placeholder="Bir kelime ara…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Kelime ara"/></label></div><div className="word-grid">{filtered.map(w=><button key={w.id} className={`word-card ${w.color}`} onClick={()=>choose(w)}><div className="word-top"><span className="word-category">{w.category}</span><span className="word-number">{String(words.indexOf(w)+1).padStart(2,'0')}</span></div><div className="word-illustration"><img src={art(w.image)} alt="" loading="lazy"/><span aria-hidden="true">{w.emoji}</span></div><h3>{w.word}</h3><p>{w.syllables}</p><div className="word-bottom"><span>Bu kelimeyi keşfet</span><span>↗</span></div></button>)}</div>{!filtered.length&&<div className="empty"><h3>Bu aramada kelime bulunamadı.</h3><button className="secondary" onClick={()=>{setQuery('');setCategory('Tümü');}}>Tüm kelimeleri göster</button></div>}<p className="source-note">ⓘ Örnek kelime havuzu. Eser listesi sağlandığında doğrulanmış kaynaklar ve alıntılar eklenecek.</p></section>
<section className="community-banner"><div className="community-mark">a<span>✦</span></div><div><div className="eyebrow">BİRLİKTE YAZDIĞIMIZ BİR SÖZLÜK</div><h2>Aynı kelime, bambaşka dünyalar.</h2><p>Diğer kelime kâşiflerinin hayallerine göz at.</p></div><button className="secondary" onClick={()=>changeTab('gallery')}>Ortak sözlüğü keşfet ↗</button></section>
</>}
{tab==='gallery'&&<section className="standalone"><div className="eyebrow">BİRLİKTE BÜYÜYEN BİR HATIRA</div><h1>Ortak <em>sözlüğümüz.</em></h1><p>Her kelimede başka bir hayal. Görevli onayından geçen kartlar burada buluşuyor.</p><button className="text-button" onClick={loadGallery}>↻ Sözlüğü yenile</button>{loading?<p role="status">Kartlar yükleniyor…</p>:gallery.length?<div className="gallery-grid">{gallery.map(c=>{const w=words.find(w=>w.id===c.wordId)!;return <button className="gallery-card" key={c.id} onClick={()=>{setCard(c);setSelected(w);setStep(4);}}><img src={c.image} alt={`${w.word} kelimesinin görseli`}/><div><span className="eyebrow">{c.mode==='ai'?'YAPAY ZEKÂ GÖRSELİ':'HAZIR GÖRSELLİ KART'}</span><h2>{w.word}</h2><p>“{c.sentence}”</p><small>{c.nickname} ↗</small></div></button>;})}</div>:!error&&<div className="empty"><span className="empty-symbol">✧</span><h2>İlk hayal seninki olsun.</h2><p>Henüz yayımlanmış kart yok. Kendi kartını oluştur ve bu sözlüğün bir parçası ol.</p><button className="primary" onClick={()=>changeTab('explore')}>Kelime seç ↗</button></div>}</section>}
{tab==='about'&&<section className="standalone about"><div className="eyebrow">KÜÇÜK BİR KEŞİF, SANA ÖZEL BİR HATIRA</div><h1>Hayalinden <em>kartına.</em></h1><p>Burada doğru bir hayal yok. Sana ait bir hayal var.</p>{[['01','Kelimeni keşfet','Bir kelime seç, anlamını tahmin et ve açıklamasını öğren.'],['02','Kendi cümleni kur','Kelimeyi günlük hayatına veya geleceğe taşı. Hazır örneklerden ilham alabilirsin; cümleyi sen yaz.'],['03','Görselini tarif et','Bir sahne düşün ve bir tarz seç. Yapay zekâ bağlantısı açıkken tarifin yeni bir görsele dönüşür. Deneme modunda hazır görsel kullanılır.'],['04','Hatıranı al, sözlüğe katıl','Kartını resim olarak indir, yazdır veya bağlantısını kopyala. Kartın görevli onayından sonra ortak sözlükte görünür.']].map(([n,t,d])=><article className="about-step" key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></article>)}<div className="info-box">Gerçek adını, okulunu veya iletişim bilgilerini yazmana gerek yok. Bir takma ad yeterli. Kart bağlantısını bilenler kartını görüntüleyebilir.</div><button className="primary" onClick={()=>changeTab('explore')}>Keşfe başla ↗</button></section>}
{error&&!selected&&!admin&&<p className="error" role="alert">{error}</p>}
</main>
<footer><a className="footer-brand" href="/">Kelimeden Hayale <span>✦</span></a><p>Geçmişten bir kelime. Gelecekten bir hayal.</p><button className="text-button" onClick={()=>{setError('');setAdmin(true);}}>Görevli girişi ↗</button><small>TEKNOFEST için hazırlanmış bağımsız etkinlik uygulaması.</small></footer>
<dialog ref={dialog} onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===dialog.current)close();}}><div className="dialog-content"><button className="close" aria-label="Pencereyi kapat" disabled={busy} onClick={close}>×</button>
{admin?<><div className="eyebrow">ETKİNLİK GÖREVLİSİ</div><h2>Kart onay alanı</h2><p>Öğrencilerin kartlarını ortak sözlükte yayımlamadan önce incele.</p>{!logged?<form onSubmit={e=>{e.preventDefault();void loadAdmin();}}><label>Görevli anahtarı<input type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} required/></label><button className="primary" disabled={loading}>{loading?'Kontrol ediliyor…':'Giriş yap'}</button></form>:<><p>{pending.length} kart onay bekliyor.</p>{pending.map(c=><article className="review" key={c.id}><img src={c.image} alt="İncelenecek kart görseli"/><div><b>{words.find(w=>w.id===c.wordId)?.word} · {c.nickname}</b><p>{c.sentence}</p><small>Görsel tarifi: {c.scene}</small><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>moderate(c.id,'approve')}>Yayımla</button><button className="text-button" disabled={busy} onClick={()=>moderate(c.id,'reject')}>Yayımlama</button></div></div></article>)}</>}</>:selected&&<>
<div className="modal-progress" aria-label={`Adım ${step} / 4`}>{['Keşfet','Cümleni kur','Görselleştir','Hatıranı al'].map((s,i)=><span className={step>=i+1?'done':''} key={s}><b>{step>i+1?'✓':i+1}</b>{s}</span>)}</div>
{step===1&&<><div className={`discovery ${selected.color}`}><span>{selected.emoji}</span><small>{selected.category} · {selected.syllables}</small><h2>{selected.word}</h2></div><h3>Sence ne anlama geliyor?</h3><label className="sr-only" htmlFor="guess">Anlam tahminin</label><input id="guess" placeholder="Aklına ilk geleni yaz…" value={guess} maxLength={160} onChange={e=>setGuess(e.target.value)}/>{!revealed?<button className="primary wide" onClick={()=>setRevealed(true)}>{guess?'Anlamını keşfet':'Tahmin etmeden anlamını gör'} ↓</button>:<><div className="meaning"><span className="eyebrow">KELİMENİN ANLAMI</span><p>{selected.meaning}</p><small>Örnek kelime havuzu · Kaynak alıntısı henüz eklenmedi.</small></div><button className="primary wide" onClick={()=>setStep(2)}>Şimdi benim cümlem ↗</button></>}</>}
{step===2&&<><div className="eyebrow">SÖZ SIRASI SENDE</div><h2>“{selected.word}” senin<br/>dünyanda nasıl yaşar?</h2><p>{selected.meaning}</p><label>Kendi cümlen<textarea maxLength={240} rows={4} placeholder={`${selected.word} kelimesini kullanarak bir cümle yaz…`} value={sentence} onChange={e=>setSentence(e.target.value)}/><small>{sentence.length}/240 · Kelimeyi cümlende kullan.</small></label><details className="hint"><summary>✧ Biraz ilham ister misin?</summary><p>Örnek: “{selected.example}”</p><p>Bu kelime gelecekteki bir şehirde veya doğada nasıl bir sahne anlatırdı?</p></details><label>Kâşif adın <small>(isteğe bağlı)</small><input maxLength={24} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="Örn. Bulut Gezgini"/><small>Gerçek adın yerine bir takma ad kullan.</small></label><div className="button-row"><button className="secondary" onClick={()=>setStep(1)}>← Geri</button><button className="primary" disabled={!sentenceValid} onClick={()=>setStep(3)}>Hayalimi görselleştir ↗</button></div></>}
{step===3&&<><div className="eyebrow">HAYALİNE BİR PENCERE AÇ</div><h2>Nasıl bir dünya görüyorsun?</h2><blockquote className="own-sentence">“{sentence}”</blockquote><label>Görselinde neler olsun?<textarea maxLength={400} rows={3} value={scene} onChange={e=>setScene(e.target.value)} placeholder="Nerede geçiyor? Neler var? Hangi renkleri görüyorsun?"/></label><button className="text-button" onClick={()=>setScene(selected.scene)}>✧ Bir sahne fikri kullan</button><fieldset><legend>Görselinin tarzı</legend><div className="style-grid">{styles.map((s,i)=><button type="button" key={s} className={style===s?'selected':''} onClick={()=>setStyle(s)}><span>{['❋','▦','✧'][i]}</span>{s}</button>)}</div></fieldset><div className="info-box">{ai?<label className="check"><input type="checkbox" checked={mode==='demo'} onChange={e=>setMode(e.target.checked?'demo':'ai')}/> Hazır görselle hızlı deneme yap</label>:<><b>Hazır görselle deneme</b><p>Canlı yapay zekâ henüz bağlı değil. Kartında kelimeye uygun hazır bir görsel kullanılacak; tarifin ve tarz seçimin kaydedilecek.</p></>}</div><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setStep(2)}>← Geri</button><button className="primary" disabled={busy||scene.trim().length<5} onClick={create}>{busy?'Kartın hazırlanıyor…':mode==='ai'?'✦ Yapay zekâ ile oluştur':'Hatıra kartımı oluştur ↗'}</button></div>{busy&&<p role="status">Hayalin hazırlanırken: Bu kelimeyi bugün başka nerede kullanabilirsin?</p>}</>}
{step===4&&card&&<><div className="result-heading"><span className="eyebrow">BU HAYAL SENİN ESERİN</span><h2>Bir kelimeden, bir hatıraya.</h2></div><article className="result-card" id="print-card"><div className="print-brand">KELİMEDEN HAYALE · TEKNOFEST HATIRASI</div><img src={card.image} alt={`${selected.word}: ${card.mode==='ai'?card.scene:'kelimeye eşlik eden hazır görsel'}`}/><div><span className="eyebrow">{card.mode==='ai'?'YAPAY ZEKÂ GÖRSELİ':'HAZIR GÖRSEL İLE OLUŞTURULDU'}</span><h2>{selected.word}</h2><p>{selected.meaning}</p><blockquote>“{card.sentence}”</blockquote><div className="result-meta"><span>✦ {card.nickname}</span><span>{new Date(card.createdAt).toLocaleDateString('tr-TR')}</span></div></div>{qr&&<div className="qr-row"><img src={qr} alt="Kart bağlantısının QR kodu"/><small>Kartını telefonunda açmak için okut.</small></div>}</article><div className="button-row result-actions"><button className="primary" onClick={download}>↓ Kartımı indir</button><button className="secondary" onClick={()=>window.print()}>Yazdır</button><button className="secondary" onClick={copy}>Bağlantıyı kopyala</button></div><p className="source-note">{card.approved===1?'Kartın ortak sözlükte yayımlandı.':card.approved===-1?'Bu kart ortak sözlükte yayımlanmadı.':'Kartın kaydedildi. Görevli onayından sonra ortak sözlükte görünecek.'}</p><button className="text-button wide" onClick={close}>Yeni bir kelime keşfet ↗</button></>}
</>}
{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
</div></dialog></>;
}
