export const words = [
{id:'tahayyul',word:'Tahayyül',syllables:'ta • hay • yül',meaning:'Bir şeyi zihinde canlandırma, hayal etme.',category:'Hayal',color:'lilac',emoji:'☁',example:'Gelecekte ağaçların arasında uçan evler tahayyül ediyorum.',scene:'Bulutların arasında, ağaçlarla kaplı küçük bir ada',image:'clouds'},
{id:'ahenk',word:'Ahenk',syllables:'a • henk',meaning:'Bir bütünü oluşturan parçaların birbirine uyumu.',category:'Sanat',color:'peach',emoji:'♫',example:'Rüzgârla yaprakların sesi güzel bir ahenk oluşturdu.',scene:'Rüzgârda dans eden rengârenk yapraklar',image:'forest'},
{id:'seher',word:'Seher',syllables:'se • her',meaning:'Sabahın gün doğmadan önceki erken vakti.',category:'Doğa',color:'yellow',emoji:'☀',example:'Seher vaktinde gökyüzü yavaşça aydınlandı.',scene:'Güneş doğmadan hemen önce sessiz bir göl',image:'sunrise'},
{id:'temasa',word:'Temaşa',syllables:'te • ma • şa',meaning:'Bir şeyi seyretme, bakıp izleme.',category:'Keşif',color:'sage',emoji:'◉',example:'Tepeden yıldızları temaşa ettik.',scene:'Bir tepeden yıldızlı gökyüzünü izleyen kâşif',image:'stars'},
{id:'tefekkur',word:'Tefekkür',syllables:'te • fek • kür',meaning:'Bir konu üzerine derinlemesine düşünme.',category:'Keşif',color:'lilac',emoji:'✧',example:'Evrenin büyüklüğü üzerine tefekkür ettim.',scene:'Kocaman evrenin içinde küçük bir gözlemevi',image:'stars'},
{id:'merhamet',word:'Merhamet',syllables:'mer • ha • met',meaning:'Başkasının güçlüğüne üzülme ve ona yardım etme isteği.',category:'Duygu',color:'peach',emoji:'♡',example:'Üşüyen kuşa merhametle yaklaştım.',scene:'Küçük bir kuşa yuva hazırlayan çocuk',image:'forest'},
{id:'seruven',word:'Serüven',syllables:'se • rü • ven',meaning:'Heyecan verici, alışılmadık olayların yaşandığı macera.',category:'Keşif',color:'sage',emoji:'↗',example:'Yeni bir gezegene yolculuğumuz bir serüvene dönüştü.',scene:'Yeşil bir vadide keşif yolculuğu',image:'forest'},
{id:'sukunet',word:'Sükûnet',syllables:'sü • kû • net',meaning:'Sessizlik, dinginlik ve sakinlik durumu.',category:'Duygu',color:'lilac',emoji:'≈',example:'Göl kıyısında sükûnet içinde oturdum.',scene:'Bulutların yansıdığı sakin bir göl',image:'clouds'},
{id:'umut',word:'Umut',syllables:'u • mut',meaning:'Güzel bir şeyin gerçekleşebileceğine duyulan inanç.',category:'Duygu',color:'yellow',emoji:'✺',example:'Diktiğimiz fidanlar geleceğe umut oldu.',scene:'Gün doğarken filizlenen küçük bir fidan',image:'sunrise'},
{id:'ufuk',word:'Ufuk',syllables:'u • fuk',meaning:'Gökyüzü ile yeryüzünün birleşmiş gibi göründüğü çizgi.',category:'Doğa',color:'peach',emoji:'◒',example:'Ufuk boyunca turuncu bulutlar uzanıyordu.',scene:'Uzak tepelerin ardında turuncu bir gökyüzü',image:'sunrise'},
{id:'hayret',word:'Hayret',syllables:'hay • ret',meaning:'Beklenmedik bir şey karşısında duyulan şaşkınlık.',category:'Duygu',color:'yellow',emoji:'✷',example:'Teleskoptan Ay’a hayretle baktım.',scene:'Ay yüzeyini ilk kez keşfeden küçük bir gezgin',image:'stars'},
{id:'zarafet',word:'Zarafet',syllables:'za • ra • fet',meaning:'Davranışta, görünüşte veya biçimde incelik ve güzellik.',category:'Sanat',color:'sage',emoji:'❋',example:'Kelebek çiçeklerin üzerinde zarafetle süzüldü.',scene:'Çiçekli bir bahçede süzülen kelebekler',image:'forest'}];
export type Word = typeof words[number];
export type Card = {id:string;wordId:string;sentence:string;nickname:string;scene:string;style:string;image:string;mode:string;createdAt:number;approved:number};
export const art=(name:string)=>`/art/${name}.png`;
