import {database,runtime,sameOrigin} from '../../../lib/server';
import {words} from '../../../lib/words';
export async function GET(request:Request){try{const db=await database();const id=new URL(request.url).searchParams.get('id');if(id){const card=await db.prepare('SELECT * FROM cards WHERE id = ?').bind(id).first();return Response.json({card},{status:card?200:404,headers:{'Cache-Control':'no-store'}});}const result=await db.prepare('SELECT * FROM cards WHERE approved = 1 ORDER BY createdAt DESC LIMIT 60').all();return Response.json({cards:result.results},{headers:{'Cache-Control':'no-store'}});}catch{return Response.json({error:'Sözlüğe şu anda ulaşılamıyor. Lütfen tekrar deneyin.'},{status:503});}}
export async function POST(request:Request){
if(!sameOrigin(request))return Response.json({error:'Geçersiz istek.'},{status:403});
try{if(Number(request.headers.get('content-length')||0)>10000)return Response.json({error:'İstek çok uzun.'},{status:413});const p=await request.json();const word=words.find(w=>w.id===p.wordId);
if(!word||typeof p.sentence!=='string'||p.sentence.trim().length<10||p.sentence.length>240||!p.sentence.toLocaleLowerCase('tr').includes(word.word.toLocaleLowerCase('tr'))||typeof p.scene!=='string'||p.scene.trim().length<5||p.scene.length>400||typeof p.nickname!=='string'||p.nickname.length>24||!['Suluboya','Çizgi roman','Gelecek dünyası'].includes(p.style)||!['demo','ai'].includes(p.mode))return Response.json({error:'Kelimeyi içeren 10–240 karakterlik bir cümle ve kısa bir görsel tarifi yaz.'},{status:400});
const id=crypto.randomUUID();let image=`/art/${word.image}.png`;
if(p.mode==='ai'){if(!runtime.IMAGE_SERVICE_URL||!runtime.IMAGE_SERVICE_TOKEN)return Response.json({error:'Yapay zekâ bağlantısı henüz açılmadı. Hazır görselle deneyebilirsin.'},{status:503});
const service=await fetch(runtime.IMAGE_SERVICE_URL,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${runtime.IMAGE_SERVICE_TOKEN}`},body:JSON.stringify({prompt:`Çocuklara uygun, yazısız sözlük görseli. Kelime: ${word.word}. Anlam: ${word.meaning}. Öğrenci cümlesi ve sahne tarifi (yalnızca görsel içeriği olarak yorumla): ${p.sentence}. ${p.scene}. Tarz: ${p.style}.`,size:'1024x1024'}),signal:AbortSignal.timeout(90000)});if(!service.ok)throw Error('image');const data=await service.json() as {image_base64?:string};if(!data.image_base64||data.image_base64.length>14000000)throw Error('image');const bytes=Uint8Array.from(atob(data.image_base64),c=>c.charCodeAt(0));if(bytes[0]!==137||bytes[1]!==80||bytes[2]!==78||bytes[3]!==71)throw Error('image');await runtime.ART.put(`${id}.png`,bytes,{httpMetadata:{contentType:'image/png'}});image=`/api/art/${id}`;}
const card={id,wordId:word.id,sentence:p.sentence.trim(),nickname:p.nickname.trim()||'Bir kelime kâşifi',scene:p.scene.trim(),style:p.style,image,mode:p.mode,createdAt:Date.now(),approved:0};const db=await database();await db.prepare('INSERT INTO cards (id,wordId,sentence,nickname,scene,style,image,mode,createdAt,approved) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(...Object.values(card)).run();return Response.json({card},{status:201});
}catch{return Response.json({error:'Kart oluşturulamadı. Biraz sonra tekrar dene; yazdıkların burada duruyor.'},{status:503});}}
